// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAjHj9kVR4NVDUQv5a4vfDiUdRHq7gZqoU',
    appId: '1:386010527533:android:4cc6192e196e2e945a85a4',
    messagingSenderId: '386010527533',
    projectId: 'realtime-messenger-c5b68',
    storageBucket: 'realtime-messenger-c5b68.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD-bLCaChY_HdcCOOxV8-p0QFuJq-o59WA',
    appId: '1:386010527533:ios:330f870baebe96fe5a85a4',
    messagingSenderId: '386010527533',
    projectId: 'realtime-messenger-c5b68',
    storageBucket: 'realtime-messenger-c5b68.appspot.com',
    androidClientId: '386010527533-he52f6eukkh02e4vsapuu9gc89r7pfc7.apps.googleusercontent.com',
    iosClientId: '386010527533-j3tmpnav2hjdu3j8hr15ao99p432ijmv.apps.googleusercontent.com',
    iosBundleId: 'com.example.whatsappUi',
  );
}
